### ISSUE TITLE
Domain list EUR currency symbol wrong in UTF-8

### ISSUE THREAD

**Issue by fhadlich** [domainmod/domainmod#12] opened 2016-10-10 09:58 UTC
In list of domain list, we have two domains with a fee in EUR. The currency symbol is displayed as "â�¬". In all other places, the currency symbol is displayed correctly.

**Comment by chetcuti** [comment] 2016-10-27 06:56
Have you always had this issue, or did it just start recently? It's very odd that this is working in some areas of the software but not others, as there should be no difference in the way the data is displayed in various locations.

If you would be open to allowing me to access your DomainMOD data, it may help speed up the investigation. I've tested this numerous times already and haven't been able to replicate the error, and I may have better luck using your actual data. For more information please visit https://domainmod.org/gethelp/

**Comment by fhadlich** [comment] 2016-10-27 10:23
Hi Greg, 

thanks four your quick response and investigation. I checked the code and our server configuration, and I might have found the culprit. 

At the moment, we have DomainMOD installed using PHP 5.3.x, and you use htmlentities against the s_default_currency Parameter from the $_SESSION array (e.g. domains/index.php, lines 2347 and 2349, as well as line 2614 for every domain record).  On our system this function uses the default charset ISO-8859-1 (see http://php.net/manual/en/function.htmlentities.php), on PHP 5.4 and newer UTF-8 is being used. 

As PHP 5.3 is greatly outdated, I guess we will be looking on upgrading in the near future and could live with the wrongly displayed fees currency until then.

Btw. the same display issue exists in other places, e.g. defined custom fields, which are shown when opening a domain in edit mode, and containing terms with special characters (in our example: name of a business owner containing an Umlaut).

Best Regards,
Frank

**Comment by chetcuti** [comment] 2016-10-28 02:57
After doing some testing I believe you're correct, that it's the htmlentities encoding type that's the cause of this issue. I've gone through and updated all of the htmlentities calls, ensure that the encoding type has been explicitly stated for each one of them. This update will be included in the next version release, which should be happening tomorrow.

Thank you so much for investigating this and figuring out what the issue was! Unless I got lucky and stumbled upon the cause by accident, I think this one would've taken me a while to figure out, so your help is greatly appreciated!

**Closed by chetcuti** 2016-10-28 02:57 UTC
