### ISSUE TITLE
Redirection fails when adding a new domain and session expires

### ISSUE THREAD

**Issue by mihail-minkov** [domainmod/domainmod#10] opened 2016-09-19 19:14 UTC
The condition is the following:

Either leave your session active for a long time and try opening the Add Domain section or open the Add Domain section and Leave it open until the session ends and then submit.

When you do either, domainmod detects that your session has ended and redirects you but the redirect is urlencoded. The result is: https://domain.com/dmod/%252Fdmod%252Fdomains%252F and you get the CodeIgniter 404 error screen.

**Comment by chetcuti** [comment] 2016-10-27 06:35
I must admit that this one has me stumped. I've tested this many times and I can't replicate the error, it just redirects me back to the login page stating that I need to login, which is the intended result. In addition to this, CodeIgniter isn't used anywhere within the software, so it's confusing that you're getting a CodeIgniter 404 page.

I'm going to keep investigating and testing this, but I have a feeling it may take a while to get to the bottom of this one.

**Comment by chetcuti** [comment] 2016-10-29 06:36
I was finally able to reproduce this issue and then trace it back to figure out what the problem is. The issue was with how the post-login URL redirect was being encoded, and it has now been fixed.

The [dev version on GitHub](https://github.com/domainmod/domainmod/tree/dev) already includes the update (02251fc49ce307afce6f2e1f34bc12844dbbce55), and it will be included in the next official release of DomainMOD (v4.01.008).

Thanks for the report!

**Closed by chetcuti** 2016-10-29 06:36 UTC
