### ISSUE TITLE
Softaculous - MySQL version error

### ISSUE THREAD

**Issue by killian-santos** [domainmod/domainmod#134] opened 2021-05-22 18:30 UTC
When I'm trying to install domainmod with Softaculous. I have this error "Required MYSQL version less than 8.0.0 AND found version is : 10.3.29".

**Comment by chetcuti** [comment] 2021-06-26 04:57
Duplicate of https://github.com/domainmod/domainmod/issues/132, closing. Please follow the discussion over there.

**Closed by chetcuti** 2021-06-26 04:57 UTC
Labels: investigating
